FROM node:latest

# Install selenium-side-runner
RUN npm install -g selenium-side-runner

# Copy the .side file to the container
COPY moneygowhere.side /tests/moneygowhere.side

# Set the entrypoint to run the tests with selenium-side-runner
ENTRYPOINT ["selenium-side-runner", "/tests/moneygowhere.side"]