name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Selenium Tests in Docker
      run: |
        # Pull the latest selenium/standalone-chrome image
        docker pull selenium/standalone-chrome
        
        # Run the container with the required volume and ports
        docker run -d --shm-size=2g --name selenium-browsers -p 4444:4444 -v $GITHUB_WORKSPACE/moneygowhere.side:/tests/moneygowhere.side selenium/standalone-chrome:latest
        
        # Run commands inside the Docker container
        # Execute commands inside the Docker container as root user
        docker exec -u root selenium-browsers bash -c 'curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -'
        docker exec -u root selenium-browsers bash -c 'apt-get install -y nodejs'
        docker exec -u root selenium-browsers bash -c 'npm install -g selenium-side-runner'
        docker exec -u root selenium-browsers bash -c 'selenium-side-runner /tests/moneygowhere.side'
        
        # Clean up the Docker container
        # docker stop selenium-browsers
        # docker rm selenium-browsers
