name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Selenium Tests in Docker
      run: |
        docker pull selenium/standalone-chrome
        docker run -d --shm-size=2g --name selenium-browsers -p 4444:4444 -v moneygowhere.side:/tests/moneygowhere.side selenium/standalone-chrome:latest
        docker exec -it selenium-browsers sudo /bin/bash
        curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
        apt-get install -y nodejs
        npm install -g selenium-side-runner
        selenium-side-runner /tests/moneygowhere.side
