name: Build and Deploy Frontend to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'

      - name: Install dependencies
        run: npm install

      - name: Download Chrome and ChromeDriver
        run: |
          # Download and install Chrome
          wget -q -O chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i chrome.deb
          sudo apt-get install -f -y
          sudo apt-get install --only-upgrade google-chrome-stable

          # Download the latest ChromeDriver version
          sudo apt-get install chromium-chromedriver

      - name: Install selenium-side-runner
        run: npm install -g selenium-side-runner
        
      - name: Print Chrome version
        run: google-chrome --version

      - name: Print ChromeDriver version
        run: chromedriver --version

      - name: Wait for 0.5 minutes
        run: sleep 30
      
      - name: Start selenium testing
        run: | 
          export PATH="$PATH:/usr/bin/google-chrome"
          echo $PATH
          selenium-side-runner moneygowhere.side

      - name: Build frontend with ESLint warnings ignored
        if: ${{ success() }}
        run: npm run build-no-eslint

      - name: Configure AWS CLI
        if: ${{ success() }}
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-southeast-2

      - name: Sync build output to S3
        if: ${{ success() }}
        run: aws s3 sync build/ s3://moneygowheredmss --delete
