name: Build and Deploy Frontend to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'

      - name: Install dependencies
        run: npm install

      - name: Download Chrome and ChromeDriver
        run: |
          # Download and install Chrome
          wget -q -O chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i chrome.deb
          sudo apt-get install -f -y
          sudo apt-get install --only-upgrade google-chrome-stable

          # Download the latest ChromeDriver version
          sudo apt-get install chromium-chromedriver

      - name: Install selenium-side-runner
        run: npm install -g selenium-side-runner
        
      - name: Print Chrome version
        run: google-chrome --version

      - name: Print ChromeDriver version
        run: chromedriver --version
        
      - name: Start frontend server
        run: npm run start &

      - name: Wait for frontend server to start
        run: |
          timeout=1000 # 5 minutes timeout
          until nc -z localhost 3000; do
            sleep 5
            timeout=$((timeout - 5))
            if [ $timeout -le 0 ]; then
              echo "Frontend server did not start within the timeout."
              exit 1
            fi
          done
