name: Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nodejs npm
        npm install -g selenium-side-runner
        
    - name: Run Selenium Tests
      run: |
        selenium-side-runner moneygowhere.side
