name: Build and Deploy Frontend to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjust the version as needed

      - name: Install dependencies
        run: npm install

      - name: Install Chrome and ChromeDriver
        run: |
          # Install Google Chrome
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install google-chrome-stable -y

          # Install ChromeDriver
          sudo apt-get install chromium-chromedriver -y
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

      - name: Print Chrome version
        run: /usr/bin/google-chrome --version

      - name: Print ChromeDriver version
        run: /usr/local/bin/chromedriver --version
        
      - name: Print Path
        run: echo $PATH

      - name: Install selenium-side-runner
        run: npm install -g selenium-side-runner

      - name: Start selenium testing
        run: selenium-side-runner moneygowhere.side
        
