name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Node.js and npm
      run: |
        sudo apt-get update
        sudo apt-get install -y nodejs npm
        
    - name: Install Chromium and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
    - name: Set Chrome Binary Path
      run: |
        echo "export CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
        
    - name: Install Selenium-Side-Runner
      run: |
        npm install -g selenium-side-runner
        
    - name: Retry Selenium Tests on Failure
      run: |
        for i in {1..3}; do selenium-side-runner moneygowhere.side && break || sleep 5; done
