name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.13.0'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 123.0.6312.105

    - name: Setup Chrome Driver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: '123.0.6312.105'

    - name: Start Xvfb
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

    - name: Install Node.js and npm
      run: |
        sudo apt-get update
        sudo apt-get install -y nodejs npm
        
    - name: Install Selenium-Side-Runner
      run: |
        chrome --version
        chromedriver --version
        npm install -g selenium-side-runner

    - name: Check Selenium Tests
      run: |
          # Determine the path to Chrome's user data directory
          CHROME_USER_DATA_DIR=$(google-chrome --version | grep -oP '\b[\d\.]+\b')/Default
          CHROME_USER_DATA_PATH="/home/runner/work/_temp/_github_home/.config/google-chrome/$CHROME_USER_DATA_DIR"

    - name: Run Selenium Tests
      run: |
        selenium-side-runner -c "chromeOptions.args=[headless]" moneygowhere.side
        # selenium-side-runner -c moneygowhere.side "goog:chromeOptions.args=[disable-infobars, headless]"
        # selenium-side-runner moneygowhere.side || exit 0
